/**
 * @file    scalar_pipeline_test.cpp
 * @brief   End-to-end scalar pipeline test — all 7 Canny stages.
 *
 * Loads `assets/<photo>`, runs every scalar stage in order:
 *
 *     gaussian -> sobel -> magnitude -> direction -> nms
 *               -> double_threshold -> hysteresis
 *
 * and writes the output of each stage to assets/test_<stage>.raw so it can
 * be inspected with tools/view_raw.py.
 *
 * No GoogleTest — assert-based with printf/cout and return codes only,
 * matching the rest of the test suite (see canny_test.cpp).
 *
 * Build & run (from the project root):
 *     make test FILE=scalar_pipeline_test
 *
 * View any stage's output, e.g.:
 *     python3 tools/view_raw.py test_gaussian.raw 100 75
 *     python3 tools/view_raw.py test_sobel_gx.raw 100 75    (auto-detects 16-bit by file size)
 *
 * Exit codes:
 *   0 — all stages completed successfully
 *   1 — one or more stages failed
 */

#include "std_types.hpp"
#include "utils.hpp"
#include "io.hpp"

#include "gaussian.hpp"
#include "sobel.hpp"
#include "magnitude.hpp"
#include "direction.hpp"
#include "nms.hpp"
#include "double_threshold.hpp"
#include "hysteresis.hpp"

#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <string>

// ─────────────────────────────────────────────────────────────────────────
// Input image — change this single line to point at a different test image.
// File must exist under ./assets/  (see tools/gen_test_image.py for more).
// ─────────────────────────────────────────────────────────────────────────
#define photo "hisham2.raw"

// rect.raw (and the other images generated by gen_test_image.py) are 100x75.
// If `photo` is pointed at a different file, update these to match it.
static constexpr uint32_t WIDTH  = 627;
static constexpr uint32_t HEIGHT = 634;

// ─────────────────────────────────────────────────────────────────────────
// Minimal pass/fail harness (project convention — no GoogleTest needed here)
// ─────────────────────────────────────────────────────────────────────────
static int g_tests_run    = 0;
static int g_tests_passed = 0;
static int g_tests_failed = 0;

#define PASS(name)                                                  \
    do                                                              \
    {                                                                \
        ++g_tests_run;                                              \
        ++g_tests_passed;                                           \
        std::cout << "  [PASS] " << (name) << "\n";                 \
    } while (0)

#define FAIL(name, msg)                                              \
    do                                                               \
    {                                                                 \
        ++g_tests_run;                                               \
        ++g_tests_failed;                                            \
        std::cout << "  [FAIL] " << (name) << " - " << (msg) << "\n";\
    } while (0)

#define CHECK_STATUS(st, name)                                                          \
    do                                                                                  \
    {                                                                                   \
        if ((st) == Status::E_OK)                                                       \
            PASS(name);                                                                 \
        else                                                                            \
            FAIL(name, "status=" + std::to_string(static_cast<int>(st)));               \
    } while (0)

using Clock = std::chrono::high_resolution_clock;

static double elapsed_ms(Clock::time_point s, Clock::time_point e)
{
    return std::chrono::duration_cast<std::chrono::duration<double, std::milli>>(e - s).count();
}

// ─────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────

/** Allocate a zeroed, 64-byte aligned uint8_t image buffer. */
static image::io::metadata_t<uint8_t> make_image(uint32_t w, uint32_t h)
{
    image::io::metadata_t<uint8_t> img;
    img.width               = w;
    img.height              = h;
    img.pixel_count         = static_cast<size_t>(w) * h;
    img.aligned_buffer_size = utils::memory::align_64(img.pixel_count * sizeof(uint8_t));
    img.buffer.reset(static_cast<uint8_t*>(
        utils::memory::aligned_alloc(64, img.aligned_buffer_size)));
    std::memset(img.buffer.get(), 0, img.aligned_buffer_size);
    return img;
}

/**
 * Wrap an already-allocated (aligned_alloc'd) int16_t gradient buffer into a
 * metadata_t so it can be dumped with save_raw(). Takes ownership of raw_buf —
 * do not free it manually afterwards.
 */
static image::io::metadata_t<int16_t> wrap_gradient(int16_t* raw_buf, uint32_t w, uint32_t h)
{
    image::io::metadata_t<int16_t> meta;
    meta.width               = w;
    meta.height              = h;
    meta.pixel_count         = static_cast<size_t>(w) * h;
    meta.aligned_buffer_size = utils::memory::align_64(meta.pixel_count * sizeof(int16_t));
    meta.buffer.reset(raw_buf);
    return meta;
}

// ─────────────────────────────────────────────────────────────────────────
// main — runs the full scalar pipeline once, saving every intermediate
// ─────────────────────────────────────────────────────────────────────────
int main()
{
    std::cout << "================================================\n";
    std::cout << " Canny Edge Detection -- Scalar Pipeline Test\n";
    std::cout << " Input image: assets/" << photo << "  (" << WIDTH << "x" << HEIGHT << ")\n";
    std::cout << "================================================\n";

    Clock::time_point t0, t1;
    Status st;

    // ── 0. Load image ───────────────────────────────────────────────────
    image::io::metadata_t<uint8_t> image;
    image.width  = WIDTH;
    image.height = HEIGHT;

    st = image::io::load_raw<uint8_t>(photo, image);
    CHECK_STATUS(st, "load_raw(" photo ")");
    if (st != Status::E_OK)
    {
        std::cout << "\nFATAL: could not load assets/" << photo << " -- aborting.\n";
        return 1;
    }

    // ── 1. Gaussian blur (in-place) ─────────────────────────────────────
    std::cout << "\n[1/7] gaussian\n";
    t0 = Clock::now();
    st = processing::gaussian_spatial_5x5<uint8_t, int32_t>(image);
    t1 = Clock::now();
    CHECK_STATUS(st, "gaussian_spatial_5x5");
    std::cout << "  time: " << elapsed_ms(t0, t1) << " ms\n";

    st = image::io::save_raw<uint8_t>("test_gaussian.raw", image);
    CHECK_STATUS(st, "save_raw(test_gaussian.raw)");

    // ── 2. Sobel ─────────────────────────────────────────────────────────
    std::cout << "\n[2/7] sobel\n";
    const size_t n = image.pixel_count;

    auto* gx_raw = static_cast<int16_t*>(utils::memory::aligned_alloc(64, n * sizeof(int16_t)));
    auto* gy_raw = static_cast<int16_t*>(utils::memory::aligned_alloc(64, n * sizeof(int16_t)));
    if (!gx_raw || !gy_raw)
    {
        FAIL("sobel alloc", "out of memory");
        return 1;
    }

    t0 = Clock::now();
    st = processing::sobel_3x3<uint8_t, int16_t>(image, gx_raw, gy_raw);
    t1 = Clock::now();
    CHECK_STATUS(st, "sobel_3x3");
    std::cout << "  time: " << elapsed_ms(t0, t1) << " ms\n";

    // Wrap gx/gy for ownership + saving; they stay alive for later stages.
    auto gx_meta = wrap_gradient(gx_raw, WIDTH, HEIGHT);
    auto gy_meta = wrap_gradient(gy_raw, WIDTH, HEIGHT);

    st = image::io::save_raw<int16_t>("test_sobel_gx.raw", gx_meta);
    CHECK_STATUS(st, "save_raw(test_sobel_gx.raw)");

    st = image::io::save_raw<int16_t>("test_sobel_gy.raw", gy_meta);
    CHECK_STATUS(st, "save_raw(test_sobel_gy.raw)");

    const int16_t* Gx = gx_meta.buffer.get();
    const int16_t* Gy = gy_meta.buffer.get();

    // ── 3. Magnitude (L1 norm) ──────────────────────────────────────────
    std::cout << "\n[3/7] magnitude\n";
    auto mag_image = make_image(WIDTH, HEIGHT);

    t0 = Clock::now();
    st = processing::MagL1<uint8_t, int16_t, uint16_t>(mag_image, Gx, Gy);
    t1 = Clock::now();
    CHECK_STATUS(st, "MagL1");
    std::cout << "  time: " << elapsed_ms(t0, t1) << " ms\n";

    st = image::io::save_raw<uint8_t>("test_magnitude.raw", mag_image);
    CHECK_STATUS(st, "save_raw(test_magnitude.raw)");

    // ── 4. Direction ─────────────────────────────────────────────────────
    std::cout << "\n[4/7] direction\n";
    auto dir_image = make_image(WIDTH, HEIGHT);

    t0 = Clock::now();
    st = processing::Direction<uint8_t, int16_t>(dir_image, Gx, Gy);
    t1 = Clock::now();
    CHECK_STATUS(st, "Direction");
    std::cout << "  time: " << elapsed_ms(t0, t1) << " ms\n";

    st = image::io::save_raw<uint8_t>("test_direction.raw", dir_image);
    CHECK_STATUS(st, "save_raw(test_direction.raw)");

    // ── 5. Non-Maximum Suppression ───────────────────────────────────────
    std::cout << "\n[5/7] nms\n";
    auto nms_image = make_image(WIDTH, HEIGHT);

    t0 = Clock::now();
    st = processing::NonMaxSuppression<uint8_t>(mag_image, dir_image, nms_image);
    t1 = Clock::now();
    CHECK_STATUS(st, "NonMaxSuppression");
    std::cout << "  time: " << elapsed_ms(t0, t1) << " ms\n";

    st = image::io::save_raw<uint8_t>("test_nms.raw", nms_image);
    CHECK_STATUS(st, "save_raw(test_nms.raw)");

    // ── 6. Double Threshold ──────────────────────────────────────────────
    std::cout << "\n[6/7] double_threshold\n";
    // Otsu-derived thresholds — robust across different input images.
    // To use fixed thresholds instead, swap for e.g.:
    //   processing::DoubleThreshold<uint8_t>(nms_image, 20, 50);
    t0 = Clock::now();
    st = processing::DoubleThresholdAuto<uint8_t>(nms_image, 0.4f);
    t1 = Clock::now();
    CHECK_STATUS(st, "DoubleThresholdAuto");
    std::cout << "  time: " << elapsed_ms(t0, t1) << " ms\n";

    st = image::io::save_raw<uint8_t>("test_double_threshold.raw", nms_image);
    CHECK_STATUS(st, "save_raw(test_double_threshold.raw)");

    // ── 7. Hysteresis ────────────────────────────────────────────────────
    std::cout << "\n[7/7] hysteresis\n";
    t0 = Clock::now();
    st = processing::Hysteresis<uint8_t>(nms_image);
    t1 = Clock::now();
    CHECK_STATUS(st, "Hysteresis");
    std::cout << "  time: " << elapsed_ms(t0, t1) << " ms\n";

    st = image::io::save_raw<uint8_t>("test_hysteresis.raw", nms_image);
    CHECK_STATUS(st, "save_raw(test_hysteresis.raw)");

    // ── Summary ──────────────────────────────────────────────────────────
    std::cout << "\n================================================\n";
    std::cout << " Results: " << g_tests_passed << "/" << g_tests_run << " passed";
    if (g_tests_failed)
        std::cout << "  (" << g_tests_failed << " FAILED)";
    std::cout << "\n================================================\n";

    return g_tests_failed == 0 ? 0 : 1;
}